/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddBand: typeof import('./src/components/form/AddBand.vue')['default']
    AddEvent: typeof import('./src/components/form/AddEvent.vue')['default']
    AddPlace: typeof import('./src/components/form/AddPlace.vue')['default']
    BandList: typeof import('./src/components/main/BandList.vue')['default']
    DeleteBand: typeof import('./src/components/form/DeleteBand.vue')['default']
    DeleteEvent: typeof import('./src/components/form/DeleteEvent.vue')['default']
    DeletePlace: typeof import('./src/components/form/DeletePlace.vue')['default']
    EditBand: typeof import('./src/components/form/EditBand.vue')['default']
    EditEvent: typeof import('./src/components/form/EditEvent.vue')['default']
    EditPlace: typeof import('./src/components/form/EditPlace.vue')['default']
    EventList: typeof import('./src/components/main/EventList.vue')['default']
    HelloWorld: (typeof import("./src/components/HelloWorld.vue"))["default"]
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PlaceList: typeof import('./src/components/main/PlaceList.vue')['default']
    PlacesList: (typeof import("./src/components/sidebar/PlacesList.vue"))["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: (typeof import("./src/components/Sidebar.vue"))["default"]
  }
}
